### ISSUE TITLE
Wrong dependency parsing for a simple sentence: "Je vous pose la question."

### ISSUE THREAD

**Issue by blegaut** [UniversalDependencies/UD_French-GSD#20]
Hello,

I played with stanza defaut pipeline for French , so UD French GSD.

I am quite surprised about the dependency parsing result for a simple sentence such as:  `Je vous pose la question.`

- The `root` is the verb `pose` as expected.
- `Je `is identified as `nsubj` as expected.
- `vous` is also identified as `nsubj`, which doesn't make sense.

![image](https://github.com/UniversalDependencies/UD_French-GSD/assets/92172115/dd1f6a20-e139-4cb9-bf3b-5fc2978aac93)

Is there any explanation for this ?

Thanks for your help

**Comment by AngledLuffa** [comment]
Simple, probably unsatisfying explanation is that almost every time `je` and `vous` show up before the verb in the treebank, they are attached with `nsubj`.  Although you might think the model would learn some rules such as `nsubj can only happen once`, there's nothing specifically that does that in the stanza depparser.  

I might use this as an opportunity to request the dev branches be updated with the unified features we talked about a couple weeks ago, @bguil, so I could rebuild models with more training data, but I'm not sure that will help in this case, since ParisStories doesn't have any sentences with both "Je" and "vous" in them.

Another possibility (which I will try tonight) is to rebuild the depparse with a transformer as the bottom layer embedding.  I hope, but can't promise, that the depparse will understand "vous" is an object in that case.

At any rate, this repo is great for errors  you may find in the data itself, but I recommend https://github.com/stanfordnlp/stanza for errors with the Stanza models trained from this data.  (If we collect enough, we can even try to fix them manually by annotating some of the bad sentences.)

**Comment by blegaut** [comment]
Thank you very much for your quick answer :)

**Comment by AngledLuffa** [comment]
If you install the stanza dev branch, there's now a depparse model which uses camembert to get better results.  For the sentence you gave, it looks like this:

```
>>> pipe = stanza.Pipeline("fr", processors={"pos": "gsd_camembert", "depparse": "gsd_camembert"})
>>> doc = pipe("Je vous pose la question.")
>>> print("{:C}".format(doc))
```

```
# text = Je vous pose la question.
# sent_id = 0
1       Je      il      PRON    _       Emph=No|Number=Sing|Person=1|PronType=Prs       3       nsubj   _       start_char=0|end_char=2|ner=O
2       vous    il      PRON    _       Emph=No|Number=Plur|Person=2|PronType=Prs       3       iobj    _       start_char=3|end_char=7|ner=O
3       pose    poser   VERB    _       Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin   0       root    _       start_char=8|end_char=12|ner=O
4       la      le      DET     _       Definite=Def|Gender=Fem|Number=Sing|PronType=Art        5       det     _       start_char=13|end_char=15|ner=O
5       question        question        NOUN    _       Gender=Fem|Number=Sing  3       obj     _       start_char=16|end_char=24|ner=O
6       .       .       PUNCT   _       _       3       punct   _       start_char=24|end_char=25|ner=O
```

Anyway, I think we've taken up enough of this repo's time!  If you want to discuss it further, see you over on the Stanza github.
