### ISSUE TITLE
CorrectForm annotation error

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_French-GSD#28]
There is an annotation error on the CorrectForm of a word:

```
# sent_id = fr-ud-train_11348
# text = Alors qu'il n'avait que 17 ans, Ibrahim s'interessa aux différentes manières d'exprimer l'heure grâce au soleil.
12      interessa       intéresser      VERB    _       Mood=Ind|Number=Sing|Person=3|Tense=Past|Typo=Yes|VerbForm=Fin  0       root    _       CorrectForm=intéressainteressa
```

Also, maybe it shouldn't, but I wonder if this ought to have `CorrectForm` on account of the missing accent on the `E`.  Perhaps it's not required to have accents on capital letters, though?

```
# sent_id = fr-ud-train_11205
# text = Evadez-vous pour un pur moment de délice
1       Evadez  évader  VERB    _       Mood=Imp|Number=Plur|Person=2|Tense=Pres|VerbForm=Fin   0       root    _       SpaceAfter=No|wordform=évadez
```

**Comment by bguil** [comment]
Thanks for the report!
 - The first example is fixed in https://github.com/surfacesyntacticud/SUD_French-GSD/commit/280dd09b530ec75068508950598100582fab1bbd
 - For the second, you're right that accents are in general not considered as required on capitals. It is consistently annotated without the feature `Typo` (see https://universal.grew.fr/?custom=6744b1fbda8cd).
